import { chromium } from "playwright-core";
const browser = await chromium.launch({ executablePath: "/Applications/Google Chrome.app/Contents/MacOS/Google Chrome" });
const page = await browser.newPage({ viewport: { width: 1440, height: 900 } });
const errors = [];
page.on("pageerror", (e) => errors.push(String(e)));
const posts = [];
page.on("request", (r) => r.method() === "POST" && posts.push(r.url()));
await page.goto("http://localhost:3000/create?to=Maya", { waitUntil: "networkidle" });
await page.evaluate(() => localStorage.removeItem("vb:draft:v1"));
await page.reload({ waitUntil: "networkidle" });
await page.waitForTimeout(400);
for (const f of ["peony", "rose", "tulip"]) await page.click(`button[aria-label^="Add a"][aria-label*=" ${f}:"]`);
await page.click('nav[aria-label=Steps] >> text=Preview');
await page.click("text=Watch it open");
await page.waitForSelector('[role=dialog] .rv[data-state="sealed"]');
const from = await page.textContent("[role=dialog] .rv-from");
await page.click("[role=dialog] .rv-envelope", { force: true });
await page.waitForSelector('[role=dialog] .rv[data-state="done"]', { timeout: 10000 });
await page.screenshot({ path: "lab/preview-overlay.png" });
await page.keyboard.press("Escape");
await page.waitForTimeout(200);
const closed = (await page.locator("[role=dialog]").count()) === 0;
const focused = await page.evaluate(() => document.activeElement?.textContent?.trim());
console.log(`${from?.includes("you sent you") || from?.includes("you") ? "PASS" : "FAIL"}  stand-in sender before signing ("${from}")`);
console.log(`${closed ? "PASS" : "FAIL"}  Esc closes the preview`);
console.log(`${focused?.includes("Watch it open") ? "PASS" : "FAIL"}  focus returns to the button ("${focused}")`);
console.log(`${posts.length === 0 ? "PASS" : "FAIL"}  previewing sends nothing to the server (${posts.length} POSTs)`);
if (errors.length) console.log("ERRORS:\n" + errors.join("\n"));
await browser.close();
